-- java22-shopping refresh test data
-- 01. DELETE

-- disable foreign keys constraint
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE T100_SUPPLIER;
TRUNCATE TABLE T101_SUPPLIER_CHAIN;
TRUNCATE TABLE T01_ITEM;
TRUNCATE TABLE T02_ITEM_GROUP;
TRUNCATE TABLE T03_ITEM_DETAIL;
TRUNCATE TABLE T04_ORDER;
TRUNCATE TABLE T05_ORDER_DETAIL;
TRUNCATE TABLE T06_ORDER_STATUS_DETAIL;
TRUNCATE TABLE T07_BILL;
TRUNCATE TABLE T08_CUSTOMER;
TRUNCATE TABLE T09_PAYMENT_METHOD;
TRUNCATE TABLE T10_ORDER_STATUS;
TRUNCATE TABLE T11_TITLE;
TRUNCATE TABLE T12_SIZE;
TRUNCATE TABLE T13_EMPLOYEE;
TRUNCATE TABLE T999_LOGGER;

-- enable foreign keys constraint
SET FOREIGN_KEY_CHECKS = 1;