CREATE DATABASE CONGTY;
USE CONGTY;

-- Phần A. Phân tích và viết các lệnh để xây dựng cơ sở dữ liệu dựa vào mô tả phía trên

-- Bảng Phòng Ban
CREATE TABLE t01_department (
	C01_DEPARTMENT_ID INT PRIMARY KEY,
    C01_DEPARTMENT_NAME VARCHAR(100) NOT NULL UNIQUE,
    C01_DEPARTMENT_MANAGER_ID INT,
    C01_MANAGER_STARTDAY DATE
);
-- Bảng Dự Án
CREATE TABLE t02_project (
	C02_PROJECT_ID INT PRIMARY KEY,
    C02_PROJECT_NAME VARCHAR(100) NOT NULL UNIQUE,
    C02_PROJECT_STARTDAY DATE NOT NULL,
    C02_PROJECT_ENDDAY DATE,
    C02_PROJECT_REVENUE DECIMAL(15, 2) CHECK (C02_PROJECT_REVENUE >=0)
);
-- Bảng Nhân Viên
CREATE TABLE t03_employee (
	C03_EMPLOYEE_ID INT PRIMARY KEY,
    C03_EMPLOYEE_NAME VARCHAR(255),
    C03_EMPLOYEE_ADDRESS VARCHAR(255),
    C03_EMPLOYEE_SALARY DECIMAL(15,2) CHECK (C03_EMPLOYEE_SALARY >= 0),
    C03_EMPLOYEE_GENDER VARCHAR(10),
    C03_EMPLOYEE_BIRTHDAY DATE,
    C03_EMPLOYEE_JOINCOMPANY_DATE DATE,
    C03_EMPLOYEE_DEPARTMENT_ID INT,
    CONSTRAINT fk_t03_t01 FOREIGN KEY (C03_EMPLOYEE_DEPARTMENT_ID) REFERENCES t01_department(C01_DEPARTMENT_ID)
);

-- Bảng Tham gia Dự Án
CREATE TABLE t04_project_employee (
	C04_EMPLOYEE_ID INT,
    C04_PROJECT_ID INT,
    C04_WORK_HOURS DECIMAL(10, 2),
    C04_PROJECT_MANAGER_ID INT,
    PRIMARY KEY (C04_EMPLOYEE_ID, C04_PROJECT_ID),
    CONSTRAINT fk_t03 FOREIGN KEY (C04_EMPLOYEE_ID) REFERENCES t03_employee(C03_EMPLOYEE_ID),
    CONSTRAINT fk_t02 FOREIGN KEY (C04_PROJECT_ID) REFERENCES t02_project(C02_PROJECT_ID),
    CONSTRAINT fk_t04_t03 FOREIGN KEY (C04_PROJECT_MANAGER_ID) REFERENCES t03_employee(C03_EMPLOYEE_ID)
);

ALTER TABLE t01_department
 ADD CONSTRAINT fk_t01_t03 FOREIGN KEY (C01_DEPARTMENT_MANAGER_ID) REFERENCES t03_employee(C03_EMPLOYEE_ID);


 