-- java22-shopping dbp 05.sql --> liên quan đến enum, constant
-- T09_PAYMENT_METHOD, T10_ORDER_STATUS

CREATE TABLE T09_PAYMENT_METHOD (
	C09_PAYMENT_METHOD_ID INT PRIMARY KEY AUTO_INCREMENT,
	C09_PAYMENT_METHOD_TYPE VARCHAR(255) NOT NULL,
    CONSTRAINT UNQ_T09_PAYMENT_METHOD_TYPE UNIQUE(C09_PAYMENT_METHOD_TYPE)
);

CREATE TABLE T10_ORDER_STATUS (
	C10_STATUS_ID INT PRIMARY KEY AUTO_INCREMENT,
	C10_STATUS_DESC VARCHAR(255) NOT NULL,
    CONSTRAINT UNQ_T10_STATUS_DESC UNIQUE(C10_STATUS_DESC)
);