DROP DATABASE IF EXISTS lesson17_exam;
CREATE DATABASE lesson17_exam CHAR SET utf8mb4;
USE lesson17_exam;

CREATE TABLE CLASS (
   CLASS_ID INT PRIMARY KEY AUTO_INCREMENT,
   CLASS_NAME VARCHAR(255) NOT NULL,
   TEACHER_NAME  VARCHAR(255) NOT NULL
);

CREATE TABLE STUDENT (
   STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
   STUDENT_NAME VARCHAR(255) NOT NULL,
   STUDENT_GENDER VARCHAR(10) NOT NULL,
   STUDENT_CLASS_ID INT NOT NULL,
   CONSTRAINT FK_STUDENT_CLASS FOREIGN KEY (STUDENT_CLASS_ID) 
                               REFERENCES CLASS(CLASS_ID)
);

CREATE TABLE RESULT (
   RESULT_STUDENT_ID INT NOT NULL,
   RESULT_SUBJECT VARCHAR(255) NOT NULL,
   RESULT_SCORE DECIMAL(4,1),
   PRIMARY KEY (RESULT_STUDENT_ID, RESULT_SUBJECT),
   CONSTRAINT FK_RESULT_STUDENT FOREIGN KEY (RESULT_STUDENT_ID) 
                               REFERENCES STUDENT(STUDENT_ID)
);

INSERT INTO CLASS(CLASS_ID, CLASS_NAME, TEACHER_NAME) VALUES
(1, '12A', 'Ho Cong Trung'),
(2, '12B', 'Dang Tu Anh'),
(3, '12C', 'Nguyen Van Tam');

INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME, STUDENT_GENDER, STUDENT_CLASS_ID) VALUES
(1, 'Dinh Thi Ngoc', 'Famale', 2),
(2, 'Nguyen Thanh Hung', 'Male', 1),
(3, 'Tran Mai Hoa', 'Famale', 2),
(4, 'Doan Quang Vinh', 'Male', 1),
(5, 'Cao Anh Dao', 'Famale', 3),
(6, 'Tran Kim Tuyen', 'Male', 3);

INSERT INTO RESULT(RESULT_STUDENT_ID, RESULT_SUBJECT, RESULT_SCORE) VALUES
(1, 'Math', 8.0),
(2, 'Literature', 7.0),
(3, 'History', 9.5),
(4, 'Math', 6.8),
(5, 'Literature', 4.9),
(6, 'History', 8.2);
-- (7, 'Math', 9.8),
-- (8, 'Literature', 7.2),
-- (9, 'History', 8.8);

SELECT * FROM CLASS;
SELECT * FROM STUDENT;
SELECT * FROM RESULT;

-- Câu 1: Primary key của bảng Result là tổ hợp của cột RESULT_STUDENT_ID và RESULT_SUBJECT 
-- để đảm bảo rằng mỗi học sinh chỉ có một điểm cho mỗi môn học 

-- Câu 2: Liệt kê tên, giới tính và tên giáo viên của tất cả học sinh

SELECT STUDENT.STUDENT_NAME,
       STUDENT.STUDENT_GENDER,
       CLASS.TEACHER_NAME
FROM STUDENT
JOIN CLASS ON STUDENT.STUDENT_CLASS_ID = CLASS.CLASS_ID
GROUP BY STUDENT.STUDENT_NAME, STUDENT.STUDENT_GENDER, CLASS.TEACHER_NAME;

-- Câu 3: Liệt kê tên giáo viên và số lượng học sinh lớp 12C

SELECT CLASS.TEACHER_NAME,
       COUNT(STUDENT.STUDENT_ID) AS number_of_students
FROM STUDENT
JOIN CLASS ON STUDENT.STUDENT_CLASS_ID = CLASS.CLASS_ID
WHERE CLASS.CLASS_NAME = '12C'
GROUP BY CLASS.TEACHER_NAME;

-- Câu 4: Liệt kê tên lớp và số lượng học sinh có điểm Toán>=8 và Văn>=8

SELECT CLASS.CLASS_NAME,
       COUNT(DISTINCT STUDENT.STUDENT_ID) AS number_of_students
FROM STUDENT
JOIN CLASS ON STUDENT.STUDENT_CLASS_ID = CLASS.CLASS_ID 
JOIN RESULT r1 ON STUDENT.STUDENT_ID = r1.RESULT_STUDENT_ID 
AND r1.RESULT_SUBJECT = 'Math' AND r1.RESULT_SCORE >= 8
JOIN RESULT r2 ON STUDENT.STUDENT_ID = r2.RESULT_STUDENT_ID 
AND r2.RESULT_SUBJECT = 'Literature' AND r2.RESULT_SCORE >= 8
GROUP BY CLASS.CLASS_NAME

 



