<<<<<<< HEAD
DB_CONFIG_URL=jdbc:mysql://localhost:3309/java22_shopping
=======
DB_CONFIG_URL=jdbc:mysql://localhost:3309/lesson17_jdbc
>>>>>>> 8fafb77 (lesson17-anchinh 12-01-2025)
DB_USER=root
DB_PASS=12345678