-- java22-shopping dbp 06.sql --> liên quan đến order
-- T04_ORDER, T05_ORDER_DETAIL, T06_ORDER_STATUS_DETAIL, T07_BILL

CREATE TABLE T04_ORDER (
	C04_ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
	C04_RECEIVER_NAME VARCHAR(255) NOT NULL,
	C04_RECEIVER_PHONE VARCHAR(255) NOT NULL,
	C04_DELIVERY_ADDRESS TEXT NOT NULL,
    C04_ORDER_TIME DATETIME NOT NULL DEFAULT(current_timestamp()),
	C04_PAYMENT_METHOD_ID INT NOT NULL,
	C04_CUSTOMER_ID INT NOT NULL,
    CONSTRAINT FK_T04_T09 FOREIGN KEY (C04_PAYMENT_METHOD_ID) REFERENCES T09_PAYMENT_METHOD(C09_PAYMENT_METHOD_ID),
    CONSTRAINT FK_T04_T08 FOREIGN KEY (C04_CUSTOMER_ID) REFERENCES T08_CUSTOMER(C08_CUSTOMER_ID)
);

CREATE TABLE T05_ORDER_DETAIL (
	C05_ORDER_ID INT NOT NULL,
	C05_ITEM_DETAIL_ID INT NOT NULL,
	C05_AMOUNT INT NOT NULL DEFAULT (0),
    PRIMARY KEY (C05_ORDER_ID, C05_AMOUNT),
    CONSTRAINT FK_T05_T04 FOREIGN KEY (C05_ORDER_ID) REFERENCES T04_ORDER(C04_ORDER_ID),
	CONSTRAINT FK_T05_T03 FOREIGN KEY (C05_ITEM_DETAIL_ID) REFERENCES T03_ITEM_DETAIL(C03_ITEM_DETAIL_ID)
);

CREATE TABLE T06_ORDER_STATUS_DETAIL (
	C06_OS_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT,
	C06_ORDER_ID INT NOT NULL,
	C06_STATUS_ID INT NOT NULL,
	C06_EMPLOYEE_ID INT NOT NULL,
	C06_LAST_UPDATED DATETIME NOT NULL DEFAULT (current_timestamp()),
	CONSTRAINT FK_T06_T04 FOREIGN KEY (C06_ORDER_ID) REFERENCES T04_ORDER(C04_ORDER_ID),
    CONSTRAINT FK_T06_T10 FOREIGN KEY (C06_STATUS_ID) REFERENCES T10_ORDER_STATUS(C10_STATUS_ID),
    CONSTRAINT FK_T06_T13 FOREIGN KEY (C06_EMPLOYEE_ID) REFERENCES T13_EMPLOYEE(C13_EMPLOYEE_ID),
    CONSTRAINT UNQ_T06_ORDER_STATUS_DETAIL UNIQUE(C06_ORDER_ID, C06_STATUS_ID)
);

CREATE TABLE T07_BILL (
	C07_BILL_ID INT PRIMARY KEY AUTO_INCREMENT,
	C07_DELIVERY_FEE DOUBLE NOT NULL,
	C07_TOTAL_OF_MONEY DOUBLE NOT NULL DEFAULT (0),
	C07_ORDER_ID INT NOT NULL,
    CONSTRAINT FK_T07_T04 FOREIGN KEY (C07_ORDER_ID) REFERENCES T04_ORDER(C04_ORDER_ID)
);



