-- create table for N-N demo(no extra columns)
DROP TABLE T15_POST_TAG;
DROP TABLE T14_POST;
DROP TABLE T16_TAG;

CREATE TABLE T14_POST(
	C14_POST_ID INT AUTO_INCREMENT,
    C14_POST_TITLE VARCHAR(255) NOT NULL,
    PRIMARY KEY (C14_POST_ID)
);

CREATE TABLE T16_TAG(
	C16_TAG_ID INT AUTO_INCREMENT,
    C16_TAG_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (C16_TAG_ID)
);

CREATE TABLE T15_POST_TAG(
	C15_POST_ID INT,
    C15_TAG_ID INT,
    PRIMARY KEY (C15_POST_ID, C15_TAG_ID),
    CONSTRAINT FK_T15_T14_POST FOREIGN KEY (C15_POST_ID) REFERENCES T14_POST(C14_POST_ID),
	CONSTRAINT FK_T15_T16_TAG FOREIGN KEY (C15_TAG_ID) REFERENCES T16_TAG(C16_TAG_ID)
);

CREATE TABLE T17_STORE(
	C17_STORE_ID INT,
    C17_STORE_NAME VARCHAR(255) NOT NULL,
    C17_ADDRESS TEXT NOT NULL,
	PRIMARY KEY (C17_STORE_ID)
);

CREATE TABLE T18_STORE_ITEM_REL(
	C18_STORE_ID INT NOT NULL,
    C18_ITEM_ID INT NOT NULL,
    C18_AMOUNT_OF_ITEMS INT NOT NULL DEFAULT 0,
    C18_ASSIGNED_DATE DATE NOT NULL,
    PRIMARY KEY (C18_STORE_ID, C18_ITEM_ID),
    CONSTRAINT FK_T18_T17_STORE FOREIGN KEY (C18_STORE_ID) REFERENCES T17_STORE(C17_STORE_ID),
    CONSTRAINT FK_T18_T01_ITEM FOREIGN KEY (C18_ITEM_ID) REFERENCES T01_ITEM(C01_ITEM_ID)
);
